/**
 * Purpose: Manages PDF rendering for editor preview using Android PdfRenderer first,
 * then PDFBox-Android as a compatibility fallback.
 * Caller: EditorViewModel, EditorScreen
 * Dependencies: Android PdfRenderer, PdfBox-Android, ParcelFileDescriptor
 * Main Functions: openPdf, renderPage, closePdf, getPageCount
 * Side Effects: Opens file descriptors, allocates Bitmaps, copies PDFs to cache
 */
package com.editpdf.online.pdf

import android.content.Context
import android.graphics.Bitmap
import android.graphics.Color
import android.graphics.pdf.PdfRenderer
import android.net.Uri
import android.os.ParcelFileDescriptor
import com.editpdf.online.analytics.CrashReporter
import com.tom_roush.pdfbox.pdmodel.PDDocument
import com.tom_roush.pdfbox.rendering.PDFRenderer
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FileOutputStream
import java.io.IOException

class PdfRendererManager(private val context: Context) {

    private var androidPdfRenderer: PdfRenderer? = null
    private var fileDescriptor: ParcelFileDescriptor? = null
    private var currentPage: PdfRenderer.Page? = null

    private var pdfBoxDocument: PDDocument? = null
    private var pdfBoxRenderer: PDFRenderer? = null
    private var cachedPdfFile: File? = null
    private var renderMode: RenderMode = RenderMode.NONE

    private val mutex = Mutex()

    private enum class RenderMode {
        NONE,
        ANDROID,
        PDFBOX
    }

    /**
     * Total number of pages in the currently opened PDF.
     */
    val pageCount: Int
        get() = when (renderMode) {
            RenderMode.ANDROID -> androidPdfRenderer?.pageCount ?: 0
            RenderMode.PDFBOX -> pdfBoxDocument?.numberOfPages ?: 0
            RenderMode.NONE -> 0
        }

    /**
     * Opens a PDF file from the given URI.
     *
     * Android PdfRenderer is fast but strict. Some valid PDFs fail there, especially PDFs
     * generated by office tools, scanners, or online converters. PDFBox is slower but more
     * tolerant, so it is used as fallback before showing an error to the user.
     */
    suspend fun openPdf(uri: Uri): Result<Int> = withContext(Dispatchers.IO) {
        mutex.withLock {
            try {
                closePdfInternal()

                val tempFile = copyToTempFileWithRetry(uri)
                if (tempFile == null || tempFile.length() <= 0) {
                    return@withContext Result.failure(
                        IOException("Unable to read PDF file. Please choose the file again.")
                    )
                }

                cachedPdfFile = tempFile

                // First try Android PdfRenderer for best performance.
                openAndroidRendererFromFile(tempFile)?.let { result ->
                    if (result.isSuccess) return@withContext result
                    closeAndroidRendererOnly()
                }

                // Fallback to direct SAF descriptor for providers that dislike temp copies.
                openAndroidRendererFromSaf(uri)?.let { result ->
                    if (result.isSuccess) return@withContext result
                    closeAndroidRendererOnly()
                }

                // Final fallback: PDFBox-Android. This handles many PDFs that Android's
                // built-in PdfRenderer rejects even when they are not password-protected.
                openPdfBoxFromFile(tempFile)?.let { result ->
                    return@withContext result
                }

                Result.failure(
                    IOException("Unable to open this PDF. The file may be corrupted, encrypted, or unsupported.")
                )
            } catch (e: SecurityException) {
                CrashReporter.logError(e, "PdfRendererManager.openPdf SecurityException")
                Result.failure(SecurityException("PDF may be password-protected"))
            } catch (e: IOException) {
                CrashReporter.logError(e, "PdfRendererManager.openPdf IOException")
                Result.failure(IOException("Unable to open PDF file: ${e.message}"))
            } catch (e: Exception) {
                CrashReporter.logError(e, "PdfRendererManager.openPdf")
                Result.failure(Exception("Unable to open PDF file: ${e.message}"))
            }
        }
    }

    /**
     * Attempts to open a PdfRenderer from a local file.
     */
    private fun openAndroidRendererFromFile(file: File): Result<Int>? {
        return try {
            val fd = ParcelFileDescriptor.open(file, ParcelFileDescriptor.MODE_READ_ONLY)
            fileDescriptor = fd

            val renderer = PdfRenderer(fd)
            androidPdfRenderer = renderer
            renderMode = RenderMode.ANDROID

            if (renderer.pageCount == 0) {
                return Result.failure(IOException("PDF has no pages"))
            }

            Result.success(renderer.pageCount)
        } catch (e: SecurityException) {
            CrashReporter.logError(e, "PdfRendererManager.openAndroidRendererFromFile SecurityException")
            Result.failure(SecurityException("PDF may be password-protected"))
        } catch (e: Exception) {
            CrashReporter.logError(e, "PdfRendererManager.openAndroidRendererFromFile")
            null
        }
    }

    /**
     * Fallback: open the PDF directly from SAF content resolver file descriptor.
     */
    private fun openAndroidRendererFromSaf(uri: Uri): Result<Int>? {
        return try {
            val afd = context.contentResolver.openFileDescriptor(uri, "r") ?: return null
            fileDescriptor = afd

            val renderer = PdfRenderer(afd)
            androidPdfRenderer = renderer
            renderMode = RenderMode.ANDROID

            if (renderer.pageCount == 0) {
                return Result.failure(IOException("PDF has no pages"))
            }

            Result.success(renderer.pageCount)
        } catch (e: SecurityException) {
            CrashReporter.logError(e, "PdfRendererManager.openAndroidRendererFromSaf SecurityException")
            Result.failure(SecurityException("PDF may be password-protected"))
        } catch (e: Exception) {
            CrashReporter.logError(e, "PdfRendererManager.openAndroidRendererFromSaf")
            null
        }
    }

    /**
     * Opens the PDF with PDFBox-Android as compatibility fallback.
     */
    private fun openPdfBoxFromFile(file: File): Result<Int>? {
        return try {
            val document = PDDocument.load(file)
            if (document.isEncrypted) {
                document.close()
                return Result.failure(SecurityException("PDF may be password-protected"))
            }

            if (document.numberOfPages == 0) {
                document.close()
                return Result.failure(IOException("PDF has no pages"))
            }

            pdfBoxDocument = document
            pdfBoxRenderer = PDFRenderer(document)
            renderMode = RenderMode.PDFBOX

            Result.success(document.numberOfPages)
        } catch (e: com.tom_roush.pdfbox.pdmodel.encryption.InvalidPasswordException) {
            CrashReporter.logError(e, "PdfRendererManager.openPdfBoxFromFile InvalidPasswordException")
            Result.failure(SecurityException("PDF may be password-protected"))
        } catch (e: Exception) {
            CrashReporter.logError(e, "PdfRendererManager.openPdfBoxFromFile")
            null
        }
    }

    /**
     * Renders the specified page to a Bitmap.
     *
     * @param pageIndex Zero-based page index
     * @param scale Scale factor for Android PdfRenderer quality. PDFBox uses matching DPI.
     * @return Bitmap of the rendered page, or null on failure
     */
    suspend fun renderPage(pageIndex: Int, scale: Float = 2.0f): Bitmap? =
        withContext(Dispatchers.IO) {
            mutex.withLock {
                when (renderMode) {
                    RenderMode.ANDROID -> renderPageWithAndroidRenderer(pageIndex, scale)
                    RenderMode.PDFBOX -> renderPageWithPdfBox(pageIndex, scale)
                    RenderMode.NONE -> null
                }
            }
        }

    private fun renderPageWithAndroidRenderer(pageIndex: Int, scale: Float): Bitmap? {
        return try {
            val renderer = androidPdfRenderer ?: return null
            if (pageIndex < 0 || pageIndex >= renderer.pageCount) return null

            currentPage?.close()

            val page = renderer.openPage(pageIndex)
            currentPage = page

            val width = (page.width * scale).toInt().coerceAtLeast(1)
            val height = (page.height * scale).toInt().coerceAtLeast(1)

            val bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)
            bitmap.eraseColor(Color.WHITE)

            page.render(
                bitmap,
                null,
                null,
                PdfRenderer.Page.RENDER_MODE_FOR_DISPLAY
            )

            page.close()
            currentPage = null

            bitmap
        } catch (e: Exception) {
            CrashReporter.logError(e, "PdfRendererManager.renderPageWithAndroidRenderer($pageIndex)")
            null
        }
    }

    private fun renderPageWithPdfBox(pageIndex: Int, scale: Float): Bitmap? {
        return try {
            val renderer = pdfBoxRenderer ?: return null
            val document = pdfBoxDocument ?: return null
            if (pageIndex < 0 || pageIndex >= document.numberOfPages) return null

            // 72 DPI is PDF native. 144 DPI matches scale 2.0f used by Android renderer.
            val dpi = (72f * scale).coerceIn(72f, 220f)
            renderer.renderImageWithDPI(pageIndex, dpi)
        } catch (e: Exception) {
            CrashReporter.logError(e, "PdfRendererManager.renderPageWithPdfBox($pageIndex)")
            null
        }
    }

    /**
     * Gets the dimensions of a specific page.
     *
     * @return Pair of (width, height), or null if unavailable
     */
    suspend fun getPageDimensions(pageIndex: Int): Pair<Int, Int>? =
        withContext(Dispatchers.IO) {
            mutex.withLock {
                when (renderMode) {
                    RenderMode.ANDROID -> getAndroidPageDimensions(pageIndex)
                    RenderMode.PDFBOX -> getPdfBoxPageDimensions(pageIndex)
                    RenderMode.NONE -> null
                }
            }
        }

    private fun getAndroidPageDimensions(pageIndex: Int): Pair<Int, Int>? {
        return try {
            val renderer = androidPdfRenderer ?: return null
            if (pageIndex < 0 || pageIndex >= renderer.pageCount) return null

            currentPage?.close()
            val page = renderer.openPage(pageIndex)
            val dimensions = Pair(page.width, page.height)
            page.close()
            currentPage = null

            dimensions
        } catch (e: Exception) {
            CrashReporter.logError(e, "PdfRendererManager.getAndroidPageDimensions($pageIndex)")
            null
        }
    }

    private fun getPdfBoxPageDimensions(pageIndex: Int): Pair<Int, Int>? {
        return try {
            val document = pdfBoxDocument ?: return null
            if (pageIndex < 0 || pageIndex >= document.numberOfPages) return null

            val mediaBox = document.getPage(pageIndex).mediaBox
            Pair(mediaBox.width.toInt(), mediaBox.height.toInt())
        } catch (e: Exception) {
            CrashReporter.logError(e, "PdfRendererManager.getPdfBoxPageDimensions($pageIndex)")
            null
        }
    }

    /**
     * Closes the current PDF and releases all resources.
     */
    suspend fun closePdf() {
        mutex.withLock {
            closePdfInternal()
        }
    }

    private fun closePdfInternal() {
        closeAndroidRendererOnly()

        try {
            pdfBoxDocument?.close()
        } catch (_: Exception) {}
        pdfBoxDocument = null
        pdfBoxRenderer = null

        try {
            cachedPdfFile?.delete()
        } catch (_: Exception) {}
        cachedPdfFile = null

        renderMode = RenderMode.NONE
    }

    private fun closeAndroidRendererOnly() {
        try {
            currentPage?.close()
        } catch (_: Exception) {}
        currentPage = null

        try {
            androidPdfRenderer?.close()
        } catch (_: Exception) {}
        androidPdfRenderer = null

        try {
            fileDescriptor?.close()
        } catch (_: Exception) {}
        fileDescriptor = null

        if (renderMode == RenderMode.ANDROID) {
            renderMode = RenderMode.NONE
        }
    }

    /**
     * Copies a SAF URI file to a temporary file with retry for SAF flakiness.
     * Verifies the copy was successful by checking file size.
     * Returns null if copy fails after retries.
     */
    private fun copyToTempFileWithRetry(uri: Uri, maxAttempts: Int = 3): File? {
        for (attempt in 1..maxAttempts) {
            try {
                val tempFile = File(context.cacheDir, "temp_pdf_${System.currentTimeMillis()}_$attempt.pdf")
                val inputStream = context.contentResolver.openInputStream(uri)
                    ?: continue

                inputStream.use { input ->
                    FileOutputStream(tempFile).use { output ->
                        input.copyTo(output)
                    }
                }

                // Verify the copy was successful
                if (tempFile.exists() && tempFile.length() > 0) {
                    return tempFile
                } else {
                    tempFile.delete()
                    CrashReporter.logMessage("PDF temp copy empty on attempt $attempt")
                }
            } catch (e: Exception) {
                CrashReporter.logError(e, "PdfRendererManager.copyToTempFile attempt $attempt")
                // Continue to next attempt
            }
        }
        return null
    }
}